namespace DeepSeek.Harness.Desktop.Services;

/// <summary>
/// CLI shim 文本生成（纯函数，可单测）。把运行时的 node + dsh 入口 + DSH_HOME 烘焙进
/// <c>dsh</c>/<c>pnpm</c> 的包装脚本，供注册到用户 PATH 后在终端直接使用（ADR
/// reference-alignment 批次四）。
/// <para>
/// 我方 online-first 运行时布局（<c>RuntimeLocator.ResolveDownloadedRuntimeDirectory</c>）：
/// <c>&lt;runtimeDir&gt;/node(.exe)</c> + <c>&lt;runtimeDir&gt;/node_modules/@deepseek-ai/dsh/lib/bin.js</c>；
/// npm 随 Node 发行包内建，但**不捆绑独立 pnpm**——dsh 的 <c>plugin</c> 子命令经
/// <c>spawnSync("pnpm")</c> 从 PATH 调用（详见 dsh 插件模块源码实证）。故 pnpm shim 只
/// 转发用户自有 pnpm，缺则诚实提示（见 ADR Alternatives：不假装自供给 pnpm）。
/// </para>
/// <para>shim 文本必须全英文：cmd/ps1 按系统代码页解析，中文注释会乱码成命令执行。</para>
/// </summary>
public static class CliShimBuilder
{
    /// <summary>生成的 shim 可识别标记（首行注释），用于区分「本应用生成的 shim」与「用户自行放置的同名文件」。</summary>
    public const string GeneratedMarker = "DeepSeek Harness Desktop - ";

    // ------------------------------------------------------------------
    // 路径转义（按目标脚本语言的字符串规则；shim 一律全英文）
    // ------------------------------------------------------------------

    /// <summary>批处理中 <c>%</c> 会被展开，需写成 <c>%%</c>。</summary>
    public static string EscapeCmd(string path) => path.Replace("%", "%%");

    /// <summary>单引号字符串中 <c>'</c> 需翻倍（PowerShell 单引号字面量）。</summary>
    public static string EscapePs1(string path) => path.Replace("'", "''");

    /// <summary>单引号字符串中 <c>'</c> 需写成 <c>'\''</c>（POSIX sh 单引号闭合-转义-重开）。</summary>
    public static string EscapeSh(string path) => path.Replace("'", "'\\''");

    // ------------------------------------------------------------------
    // dsh shim
    // ------------------------------------------------------------------

    /// <summary>Windows <c>dsh.cmd</c>。</summary>
    public static string BuildDshCmd(string runtimeDir, string dshHome) =>
        DshCmdTemplate
            .Replace("@RUNTIME_DIR@", EscapeCmd(runtimeDir))
            .Replace("@DSH_HOME@", EscapeCmd(dshHome));

    /// <summary>Windows <c>dsh.ps1</c>。</summary>
    public static string BuildDshPs1(string runtimeDir, string dshHome) =>
        DshPs1Template
            .Replace("@RUNTIME_DIR@", EscapePs1(runtimeDir))
            .Replace("@DSH_HOME@", EscapePs1(dshHome));

    /// <summary>Unix <c>dsh</c> 包装脚本（POSIX sh）。</summary>
    public static string BuildDshSh(string runtimeDir, string dshHome) =>
        DshShTemplate
            .Replace("@RUNTIME_DIR@", EscapeSh(runtimeDir))
            .Replace("@DSH_HOME@", EscapeSh(dshHome));

    /// <summary>Windows <c>pnpm.cmd</c>。</summary>
    public static string BuildPnpmCmd() => PnpmCmdTemplate;

    /// <summary>Windows <c>pnpm.ps1</c>。</summary>
    public static string BuildPnpmPs1() => PnpmPs1Template;

    /// <summary>Unix <c>pnpm</c> 包装脚本（POSIX sh）。</summary>
    public static string BuildPnpmSh() => PnpmShTemplate;

    // ------------------------------------------------------------------
    // 模板（非内插原始字符串：@RUNTIME_DIR@ / @DSH_HOME@ 为待替换令牌，花括号与 $ 均为字面量）
    // ------------------------------------------------------------------

    private const string DshCmdTemplate = """
        @echo off
        rem DeepSeek Harness Desktop - dsh command shim (generated)
        rem Do not edit: regenerated by the desktop app on startup.
        setlocal
        set "DSH_HOME=@DSH_HOME@"
        set "DSH_TELEMETRY_DISABLED=1"
        set "RUNTIME_DIR=@RUNTIME_DIR@"
        set "DSH_BIN=%RUNTIME_DIR%\node_modules\@deepseek-ai\dsh\lib\bin.js"

        rem Prefer a user-installed dsh on PATH (skip our own shim dir), fall back to the
        rem desktop runtime. Preserves your own dsh binary and its config; nothing is overwritten.
        set "SELF_PREFIX=%~dp0"
        set "SELF_PREFIX=%SELF_PREFIX:~0,-1%"
        set "USER_DSH="
        for /f "delims=" %%d in ('where dsh 2^>nul') do (
          if not defined USER_DSH (
            if /i not "%%d"=="%SELF_PREFIX%\dsh.cmd" (
              if /i not "%%d"=="%SELF_PREFIX%\dsh.exe" (
                if /i not "%%d"=="%SELF_PREFIX%\dsh.bat" (
                  if /i "%%~xd"==".cmd" set "USER_DSH=%%d"
                  if /i "%%~xd"==".exe" set "USER_DSH=%%d"
                  if /i "%%~xd"==".bat" set "USER_DSH=%%d"
                )
              )
            )
          )
        )
        if defined USER_DSH (
          call "%USER_DSH%" %*
          exit /b %ERRORLEVEL%
        )

        rem Resolve node: DSH_NODE (desktop child) -> compatible local node -> runtime node.
        set "NODE="
        if defined DSH_NODE (
          set "NODE=%DSH_NODE%"
          goto :found_node
        )
        where node >nul 2>nul
        if errorlevel 1 goto :use_runtime
        for /f "tokens=1,2 delims=v." %%a in ('node --version 2^>nul ^| findstr /b "v"') do set "NODE_MAJOR=%%a" & set "NODE_MINOR=%%b"
        if not defined NODE_MAJOR goto :use_runtime
        if %NODE_MAJOR% GEQ 24 goto :use_path_node
        if %NODE_MAJOR% EQU 22 if defined NODE_MINOR if %NODE_MINOR% GEQ 15 goto :use_path_node
        if %NODE_MAJOR% EQU 23 if defined NODE_MINOR if %NODE_MINOR% GEQ 8 goto :use_path_node
        goto :use_runtime
        :use_path_node
        set "NODE=node"
        goto :found_node
        :use_runtime
        if not exist "%RUNTIME_DIR%\node.exe" goto :no_node
        set "NODE=%RUNTIME_DIR%\node.exe"
        set "PATH=%RUNTIME_DIR%;%PATH%"

        :found_node
        if not exist "%DSH_BIN%" goto :no_cli
        "%NODE%" "%DSH_BIN%" %*
        exit /b %ERRORLEVEL%

        :no_cli
        echo [dsh] Harness CLI not found. Please run DeepSeek Harness Desktop to install it first. 1>&2
        exit /b 1

        :no_node
        echo [dsh] Node.js runtime not found. Please run DeepSeek Harness Desktop to install it first. 1>&2
        exit /b 1
        """;

    private const string DshPs1Template = """
        # DeepSeek Harness Desktop - dsh command shim (generated)
        # Do not edit: regenerated by the desktop app on startup.
        $ErrorActionPreference = "Stop"
        $runtimeDir = '@RUNTIME_DIR@'
        $dshHome = '@DSH_HOME@'
        $dshBin = Join-Path $runtimeDir 'node_modules\@deepseek-ai\dsh\lib\bin.js'

        # Prefer a user-installed dsh on PATH (skip our own shim dir), fall back to the
        # desktop runtime. Preserves your own dsh binary and its config.
        $selfDir = $PSScriptRoot.TrimEnd('\') + '\'
        $userDsh = Get-Command dsh -All -ErrorAction SilentlyContinue |
            Where-Object { $_.Source -and -not $_.Source.StartsWith($selfDir, [System.StringComparison]::OrdinalIgnoreCase) } |
            Select-Object -First 1
        if ($userDsh) {
            & $userDsh.Source @args
            exit $LASTEXITCODE
        }

        # Resolve node: DSH_NODE (desktop child) -> compatible local node -> runtime node.
        $node = $null
        if ($env:DSH_NODE -and (Test-Path -LiteralPath $env:DSH_NODE)) { $node = $env:DSH_NODE }
        if (-not $node) {
            $local = Get-Command node -ErrorAction SilentlyContinue
            if ($local) {
                try {
                    $v = & node --version 2>$null
                    if ($v -match '^v(\d+)\.(\d+)') {
                        $maj = [int]$matches[1]; $min = [int]$matches[2]
                        if (($maj -eq 22 -and $min -ge 15) -or ($maj -eq 23 -and $min -ge 8) -or $maj -ge 24) { $node = 'node' }
                    }
                } catch { }
            }
        }
        if (-not $node) {
            $bundled = Join-Path $runtimeDir 'node.exe'
            if (Test-Path -LiteralPath $bundled) {
                $node = $bundled
                $env:PATH = $runtimeDir + ';' + $env:PATH
            }
        }
        if (-not $node) { Write-Error '[dsh] Node.js runtime not found. Please run DeepSeek Harness Desktop to install it first.'; exit 1 }
        if (-not (Test-Path -LiteralPath $dshBin)) { Write-Error '[dsh] Harness CLI not found. Please run DeepSeek Harness Desktop to install it first.'; exit 1 }

        $env:DSH_HOME = $dshHome
        $env:DSH_TELEMETRY_DISABLED = '1'
        & $node $dshBin @args
        exit $LASTEXITCODE
        """;

    private const string DshShTemplate = """
        #!/bin/sh
        # DeepSeek Harness Desktop - dsh command shim (generated)
        # Do not edit: regenerated by the desktop app on startup.
        RUNTIME_DIR='@RUNTIME_DIR@'
        DSH_BIN="$RUNTIME_DIR/node_modules/@deepseek-ai/dsh/lib/bin.js"
        DSH_HOME='@DSH_HOME@'

        # Prefer a user-installed dsh on PATH (skip our own shim dir), fall back to the
        # desktop runtime. Preserves your own dsh binary and its config.
        SELF_DIR=$(cd "$(dirname "$0")" && pwd)
        IFS=:
        for dir in $PATH; do
          if [ "$dir" = "$SELF_DIR" ]; then continue; fi
          if [ -x "$dir/dsh" ]; then
            exec "$dir/dsh" "$@"
          fi
        done
        unset IFS

        # Resolve node: DSH_NODE (desktop child) -> compatible local node -> runtime node.
        NODE=""
        if [ -n "$DSH_NODE" ] && [ -x "$DSH_NODE" ]; then
          NODE="$DSH_NODE"
        fi
        if [ -z "$NODE" ] && command -v node >/dev/null 2>&1; then
          NODE_V=$(node --version 2>/dev/null)
          NODE_MAJOR=$(printf '%s' "$NODE_V" | awk -F. '{ gsub(/^v/, "", $1); print $1 }')
          NODE_MINOR=$(printf '%s' "$NODE_V" | awk -F. '{ print $2 }')
          if [ -n "$NODE_MAJOR" ] && [ "$NODE_MAJOR" -ge 24 ] 2>/dev/null || \
             [ "$NODE_MAJOR" -eq 22 ] && [ "$NODE_MINOR" -ge 15 ] 2>/dev/null || \
             [ "$NODE_MAJOR" -eq 23 ] && [ "$NODE_MINOR" -ge 8 ] 2>/dev/null; then
            NODE="node"
          fi
        fi
        if [ -z "$NODE" ]; then
          if [ -x "$RUNTIME_DIR/node" ]; then
            NODE="$RUNTIME_DIR/node"
            export PATH="$RUNTIME_DIR:$PATH"
          fi
        fi
        if [ -z "$NODE" ]; then
          echo "[dsh] Node.js runtime not found. Please run DeepSeek Harness Desktop to install it first." >&2
          exit 1
        fi
        if [ ! -f "$DSH_BIN" ]; then
          echo "[dsh] Harness CLI not found. Please run DeepSeek Harness Desktop to install it first." >&2
          exit 1
        fi

        export DSH_HOME
        export DSH_TELEMETRY_DISABLED=1
        exec "$NODE" "$DSH_BIN" "$@"
        """;

    private const string PnpmCmdTemplate = """
        @echo off
        rem DeepSeek Harness Desktop - pnpm command shim (generated)
        rem Do not edit: regenerated by the desktop app on startup.
        rem This desktop distribution does not bundle pnpm; forward to a user-installed pnpm.
        set "SELF_PREFIX=%~dp0"
        set "SELF_PREFIX=%SELF_PREFIX:~0,-1%"
        set "USER_PNPM="
        for /f "delims=" %%p in ('where pnpm 2^>nul') do (
          if not defined USER_PNPM (
            if /i not "%%p"=="%SELF_PREFIX%\pnpm.cmd" (
              if /i not "%%p"=="%SELF_PREFIX%\pnpm.exe" (
                if /i not "%%p"=="%SELF_PREFIX%\pnpm.bat" (
                  if /i "%%~xp"==".cmd" set "USER_PNPM=%%p"
                  if /i "%%~xp"==".exe" set "USER_PNPM=%%p"
                  if /i "%%~xp"==".bat" set "USER_PNPM=%%p"
                )
              )
            )
          )
        )
        if defined USER_PNPM (
          call "%USER_PNPM%" %*
          exit /b %ERRORLEVEL%
        )
        echo [pnpm] pnpm not found. Please install pnpm or run DeepSeek Harness Desktop to use the bundled tooling. 1>&2
        exit /b 1
        """;

    private const string PnpmPs1Template = """
        # DeepSeek Harness Desktop - pnpm command shim (generated)
        # Do not edit: regenerated by the desktop app on startup.
        $ErrorActionPreference = "Stop"
        $selfDir = $PSScriptRoot.TrimEnd('\') + '\'
        $userPnpm = Get-Command pnpm -All -ErrorAction SilentlyContinue |
            Where-Object { $_.Source -and -not $_.Source.StartsWith($selfDir, [System.StringComparison]::OrdinalIgnoreCase) } |
            Select-Object -First 1
        if ($userPnpm) {
            & $userPnpm.Source @args
            exit $LASTEXITCODE
        }
        Write-Error '[pnpm] pnpm not found. Please install pnpm or run DeepSeek Harness Desktop to use the bundled tooling.'
        exit 1
        """;

    private const string PnpmShTemplate = """
        #!/bin/sh
        # DeepSeek Harness Desktop - pnpm command shim (generated)
        # Do not edit: regenerated by the desktop app on startup.
        SELF_DIR=$(cd "$(dirname "$0")" && pwd)
        IFS=:
        for dir in $PATH; do
          if [ "$dir" = "$SELF_DIR" ]; then continue; fi
          if [ -x "$dir/pnpm" ]; then
            exec "$dir/pnpm" "$@"
          fi
        done
        unset IFS
        echo "[pnpm] pnpm not found. Please install pnpm or run DeepSeek Harness Desktop to use the bundled tooling." >&2
        exit 1
        """;
}
