namespace DeepSeek.Harness.Desktop.Services;

/// <summary>
/// CLI shim 文本生成（纯函数，可单测）。dsh 已全局安装在用户 PATH（ADR simple-shell-single-global-dsh），
/// 桌面无需再生成 dsh shim；此处只保留 <c>pnpm</c> 的转发包装脚本，供注册到用户 PATH 后在终端直接使用。
/// <para>
/// 本分布不捆绑独立 pnpm——dsh 的 <c>plugin</c> 子命令经 <c>spawnSync("pnpm")</c> 从 PATH 调用（详见 dsh
/// 插件模块源码实证）。故 pnpm shim 只转发用户自有 pnpm，缺则诚实提示。
/// </para>
/// <para>shim 文本必须全英文：cmd/ps1 按系统代码页解析，中文注释会乱码成命令执行。</para>
/// </summary>
public static class CliShimBuilder
{
    /// <summary>生成的 shim 可识别标记（首行注释），用于区分「本应用生成的 shim」与「用户自行放置的同名文件」。</summary>
    public const string GeneratedMarker = "DeepSeek Harness Desktop - ";

    /// <summary>Windows <c>pnpm.cmd</c>。</summary>
    public static string BuildPnpmCmd() => PnpmCmdTemplate;

    /// <summary>Windows <c>pnpm.ps1</c>。</summary>
    public static string BuildPnpmPs1() => PnpmPs1Template;

    /// <summary>Unix <c>pnpm</c> 包装脚本（POSIX sh）。</summary>
    public static string BuildPnpmSh() => PnpmShTemplate;

    private const string PnpmCmdTemplate = """
        @echo off
        rem DeepSeek Harness Desktop - pnpm command shim (generated)
        rem Do not edit: regenerated by the desktop app on startup.
        rem This desktop distribution does not bundle pnpm; forward to a user-installed pnpm.
        set "SELF_PREFIX=%~dp0"
        set "SELF_PREFIX=%SELF_PREFIX:~0,-1%"
        set "USER_PNPM="
        for /f "delims=" %%p in ('where pnpm 2^>nul') do (
          if not defined USER_PNPM (
            if /i not "%%p"=="%SELF_PREFIX%\pnpm.cmd" (
              if /i not "%%p"=="%SELF_PREFIX%\pnpm.exe" (
                if /i not "%%p"=="%SELF_PREFIX%\pnpm.bat" (
                  if /i "%%~xp"==".cmd" set "USER_PNPM=%%p"
                  if /i "%%~xp"==".exe" set "USER_PNPM=%%p"
                  if /i "%%~xp"==".bat" set "USER_PNPM=%%p"
                )
              )
            )
          )
        )
        if defined USER_PNPM (
          call "%USER_PNPM%" %*
          exit /b %ERRORLEVEL%
        )
        echo [pnpm] pnpm not found. Please install pnpm, or run DeepSeek Harness Desktop. 1>&2
        exit /b 1
        """;

    private const string PnpmPs1Template = """
        # DeepSeek Harness Desktop - pnpm command shim (generated)
        # Do not edit: regenerated by the desktop app on startup.
        $ErrorActionPreference = "Stop"
        $selfDir = $PSScriptRoot.TrimEnd('\') + '\'
        $userPnpm = Get-Command pnpm -All -ErrorAction SilentlyContinue |
            Where-Object { $_.Source -and -not $_.Source.StartsWith($selfDir, [System.StringComparison]::OrdinalIgnoreCase) } |
            Select-Object -First 1
        if ($userPnpm) {
            & $userPnpm.Source @args
            exit $LASTEXITCODE
        }
        Write-Error '[pnpm] pnpm not found. Please install pnpm, or run DeepSeek Harness Desktop.'
        exit 1
        """;

    private const string PnpmShTemplate = """
        #!/bin/sh
        # DeepSeek Harness Desktop - pnpm command shim (generated)
        # Do not edit: regenerated by the desktop app on startup.
        SELF_DIR=$(cd "$(dirname "$0")" && pwd)
        IFS=:
        for dir in $PATH; do
          if [ "$dir" = "$SELF_DIR" ]; then continue; fi
          if [ -x "$dir/pnpm" ]; then
            exec "$dir/pnpm" "$@"
          fi
        done
        unset IFS
        echo "[pnpm] pnpm not found. Please install pnpm, or run DeepSeek Harness Desktop." >&2
        exit 1
        """;
}
